{% set version = "2.4.0" %}
{% set sha256 = "bdb1bc84229f2bb81c9a4b5ee005b4f586895c320f504fbd1f983a0ef1cd6bb6" %}

package:
  name: vcfdist
  version: {{ version }}

source:
  url: https://github.com/TimD1/vcfdist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("vcfdist", max_pin="x.x") }}

requirements:
  build: 
    - make
    - {{ compiler('cxx') }}
  host:
    - htslib
  run:
    - htslib

test:
  commands:
    - vcfdist --version

about:
  summary: 'vcfdist: benchmarking phased germline variant calls in VCF format'
  home: https://github.com/TimD1/vcfdist
  license: GNU GPL v3
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://github.com/TimD1/vcfdist/wiki

extra:
  maintainers:
    - Tim Dunn
  identifiers:
    - https://zenodo.org/doi/10.5281/zenodo.8368282
